const infos = {
  login: 'jijip41',
  id: 78619809,
  node_id: 'MDQ6VXNlcjc4NjE5ODA5',
  avatar_url: 'https://avatars.githubusercontent.com/u/78619809?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jijip41',
  html_url: 'https://github.com/jijip41',
  followers_url: 'https://api.github.com/users/jijip41/followers',
  following_url: 'https://api.github.com/users/jijip41/following{/other_user}',
  gists_url: 'https://api.github.com/users/jijip41/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/jijip41/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jijip41/subscriptions',
  organizations_url: 'https://api.github.com/users/jijip41/orgs',
  repos_url: 'https://api.github.com/users/jijip41/repos',
  events_url: 'https://api.github.com/users/jijip41/events{/privacy}',
  received_events_url: 'https://api.github.com/users/jijip41/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jihye Pak',
  company: null,
  blog: '',
  location: 'London',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: 'jihye_pak',
  public_repos: 32,
  public_gists: 0,
  followers: 10,
  following: 17,
  created_at: '2021-02-05T20:14:29Z',
  updated_at: '2021-09-09T19:14:49Z',
};

export default infos;
